### ISSUE TITLE
Bug [1.20.1]: RESOURCES RELOAD AFTER BOOT

### ISSUE THREAD

**Issue by Camawama** [Zepalesque/The-Aether-Redux#21] opened 2023-10-26 04:29 UTC
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
MOD VERSION: 1.2
FORGE VERSION: 1.20.1-47.2.1

**Describe the bug**
When this mod is added, there is a redundant resource reload when on the title screen. It makes load times even slower.

**To Reproduce**
1. Install the mod
2. Boot up the game

**Expected behavior**
Resources should be loaded during boot.

**Comment by Zepalesque** [comment] 2023-10-26 16:09
hmm, yeah I’ll look into that, this is only supposed to happen on the very first startup

**Comment by Camawama** [comment] 2023-10-27 00:18
If it helps, I am using open loader to load resource packs for my modpack.

**Comment by Zepalesque** [comment] 2023-10-27 01:36
tbf this has actually been happening in my dev environment too, I just didn’t realize the potential impacts on already-long loading times, so I think it’s just some issue with how I set up the logic, but if that doesn’t work I’ll look into that too

**Comment by Camawama** [comment] 2023-10-27 02:09
My modpack (CamaCraft) has over 260 mods so when resources reload...it takes ages 😅 

I am happy to report bugs to mod devs! Working on a large modpack really helps me find tons of bugs. hopefully, it's an easy fix for you and isn't too stressful or time-consuming. Thank you for the awesome mod btw!

**Comment by Zepalesque** [comment] 2023-10-31 04:53
This should now be fixed as of v1.3!

**Comment by Gbergz** [comment] 2023-10-31 14:34
This still happens on v1.3

**Comment by Zepalesque** [comment] 2023-10-31 16:37
strange, I’ll look into it

**Comment by Zepalesque** [comment] 2023-10-31 17:46
> [This still happens on v1.3](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/issues/21#issuecomment-1787343273)

hmm, I can't seem to reproduce the issue, what other mods are you using?

**Comment by Zepalesque** [comment] 2023-10-31 17:47
whoops accidentially closed it but yeah still can't seem to reproduce

**Comment by Zepalesque** [comment] 2023-10-31 20:45
does it do it every time or just once? because if it just does it one time then that’s intended, that’s how it makes sure the textures are reloaded after applying the built-in pack
if it does it every time, then yesh that’s odd
I have an idea of how to potentially remove the extra reload entirely though, so I might try that at some point as well

**Comment by Gbergz** [comment] 2023-10-31 23:13
Every time yeah

**Comment by Zepalesque** [comment] 2023-11-05 03:53
hmm yeah I’ll look into it then, odd

**Comment by Zepalesque** [comment] 2023-11-07 02:39
unfortunately because of some fairly critical bugs that need patches pretty quick I'll have to delay this to the update after the next one, but I'll look into it once that update is out

**Comment by RuafuMan-Obs** [comment] 2023-12-10 09:02
got same issue on 1.3.3  1.20.1 ,but on my last world with same mod version this issue isn't happening ,perhaps because this time I added deep aether?

**Comment by Zepalesque** [comment] 2023-12-31 00:15
will be fixed in the next update, I changed it so that it doesn't need an extra reload at all as it applies the packs before the initial resource load

**Comment by Gbergz** [comment] 2024-03-01 23:33
Still happens on latest update (v1.3.4). Can't update this mod past v1.0.1 due to this issue unfortunately.

**Comment by Zepalesque** [comment] 2024-03-02 03:09
try the 2.0 prerelease if you're on 1.20.1 at least 
https://github.com/Zepalesque/The-Aether-Redux/releases

**Comment by Zepalesque** [comment] 2024-03-07 04:20
fixed in version 2.0

**Closed by Zepalesque** 2024-03-07 04:20 UTC
Labels: bug-report, pending-update
