### ISSUE TITLE
Bug [1.19.2]: Crash

### ISSUE THREAD

**Issue by togera13** [Zepalesque/The-Aether-Redux#34] opened 2023-11-14 22:41 UTC
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
1.3.3
**Describe the bug**
Crash

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash report (if necessary and/or applicable)**
[crash-2023-11-14_17.37.54-client.txt](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13358015/crash-2023-11-14_17.37.54-client.txt)

**Log file (should be titled latest.log, if applicable)**
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13358018/latest.log)

**Additional context**

**Comment by Zepalesque** [comment] 2023-11-21 22:07
hmm, this appears to be caused by possibly the tag collection for quicksoil being iterated through before being instantiated? a null check and or a non-null starting value should fix this, this’ll be fixed in 1.3.4 or whatever the next version that comes out will be

**Comment by Zepalesque** [comment] 2023-12-31 00:16
fixed in v1.3.4

**Closed by Zepalesque** 2023-12-31 00:16 UTC
Labels: bug-report
